#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/dss-owl-logo-light.png"
logo_darkmode = "images/dss-owl-logo-dark.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "300px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Data Science Skills logo"
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#!" # contact form works with [https://airform.io/] or [https://formspree.io]
# demo form action
demo_form_action = "#!" # demo form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""
# copyright
theme_copyright = true
copyright = "Copyright Leah A Wasser, 2023"

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format. example - "images/preloader.gif"

# Navigation button
[navigation_button]
enable = false
label = "Get a Demo"
link = "get-demo/"

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["data science", "open science", "python"]
description = "This is meta description"
author = "Data Science Skills"
image = "images/logo.png"                             # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = true
url = ""      # your matomo url
id = ""       # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site footer info ########################
# [[social]]
# title = "facebook"
# icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"

# [[social]]
# title = "twitter"
# icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"

# [[social]]
# title = "instagram"
# icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"

[[social]]
title = "github"
icon = "fab fa-github"                              # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.github.com/data-science-skills"

# [[social]]
# title = "linkedin"
# icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#!"
